In [54]:

def het_weer_stad(stad):
    import requests
    from bs4 import BeautifulSoup
    import pandas as pd
    
    url = 'https://www.meteo.be/nl/' + str(stad)
    response = requests.get(url)
    html = response.text
    
    soup = BeautifulSoup(html, 'html.parser')
    dagen = soup.find_all('day-of-the-week')
    
    headers = ['Dag', 'Min.Temp (°C)', 'Max.Temp (°C)', 'Vocht (%)', 'Wind (Bft)']
    
    lijst_rijen = []
    
    for dag in dagen:
        naam = dag['name']
        mintemp = dag['mintemp']
        maxtemp = dag['maxtemp']
        vocht = dag['humiditypct']
        wind = dag['windspeedbft']
    
        dag_info = [naam, mintemp, maxtemp, vocht, wind]
        lijst_rijen.append(dag_info)
    
    tabel_weer = pd.DataFrame(data = lijst_rijen, columns = headers)
    tabel_weer = tabel_weer.replace(to_replace = '', value = 'NaN')

    # in plaats van naam van de dag willen we 'Vandaag' zien => Vandaag + Vannacht (duidelijke info)!
        # om de 1ste waarde te veranderen hebben we een filter nodig die we in '.replace()' kunnen steken!
    filt = tabel_weer.loc[0, 'Dag']
    tabel_weer = tabel_weer.replace(to_replace = filt, value = 'Vandaag').set_index(keys = 'Dag')
    
    return tabel_weer

In [48]:
het_weer_stad('brussel')

          Min.Temp (°C) Max.Temp (°C) Vocht (%) Wind (Bft)
Dag
Vandaag             NaN            26         0          2
Vannacht             13           NaN         0          2
Donderdag            13            28         0          2
Vrijdag              19            26         0          3
Zaterdag             13            25        40          2
Zondag                9            14         0          3
Maandag               7            14         0          3
Dinsdag               6            14         0          2

In [52]:
het_weer_stad('antwerpen')

          Min.Temp (°C) Max.Temp (°C) Vocht (%) Wind (Bft)
Dag
Vandaag             NaN            24         0          1
Vannacht             14           NaN         0          3
Donderdag            14            27         0          2
Vrijdag              17            25         0          2
Zaterdag             11            24         0          2
Zondag                9            14         0          3
Maandag               7            14         0          3
Dinsdag               6            14         0          2

In [56]:
het_weer_stad('koksijde')

          Min.Temp (°C) Max.Temp (°C) Vocht (%) Wind (Bft)
Dag
Vandaag             NaN            23         0          2
Vannacht              9           NaN         0          3
Donderdag             9            26         0          2
Vrijdag              14            22         0          2
Zaterdag              9            21         0          2
Zondag               10            12        50          5
Maandag               9            11       100          4
Dinsdag               7            11        50          3